import { BaseAgent } from './base-agent.js';
import { AgentRole, ProjectContext, AgentTask, ProjectPhase } from '../types.js';
import { ProductManagerAgent } from './product-manager.js';
import { TechLeadAgent } from './tech-lead.js';
import { DeveloperAgent } from './developer.js';
import { QAEngineerAgent } from './qa-engineer.js';
import { DevOpsEngineerAgent } from './devops-engineer.js';
import { FileSystemService } from '../services/filesystem.js';
import { GitService } from '../services/git.js';
import { config } from '../config.js';

export class OrchestratorAgent extends BaseAgent {
  private agents: Map<AgentRole, BaseAgent> = new Map();
  private projectContext: ProjectContext;
  private fs: FileSystemService;
  private git: GitService;

  constructor(context: ProjectContext) {
    super('orchestrator', context);
    this.projectContext = context;
    this.fs = new FileSystemService();
    this.git = new GitService();
    this.initializeAgents();
  }

  protected getRoleResponsibilities(): string {
    return `- Coordinate and manage the autonomous development team
- Orchestrate the development workflow from PRD to prototype
- Assign tasks to appropriate agents based on project phase
- Monitor progress and ensure quality gates are met
- Manage project context and shared state
- Facilitate communication between agents
- Ensure project completion and delivery
- Handle errors and recovery procedures`;
  }

  async execute(task: AgentTask): Promise<any> {
    this.logTaskStart(task);

    try {
      switch (task.title.toLowerCase()) {
        case 'orchestrate_project':
          return await this.orchestrateProject(task);
        case 'manage_workflow':
          return await this.manageWorkflow(task);
        case 'assign_tasks':
          return await this.assignTasks(task);
        case 'monitor_progress':
          return await this.monitorProgress(task);
        case 'validate_phase':
          return await this.validatePhase(task);
        case 'handle_error':
          return await this.handleError(task);
        case 'generate_project_summary':
          return await this.generateProjectSummary(task);
        default:
          throw new Error(`Unknown task: ${task.title}`);
      }
    } catch (error) {
      this.logTaskError(task, error as Error);
      throw error;
    }
  }

  private async orchestrateProject(task: AgentTask): Promise<{ project_result: any }> {
    const prdContent = task.result?.prd_content;
    const projectName = task.result?.project_name || 'Auto-Generated Project';
    const projectDescription = task.result?.project_description || 'Project generated by MCP Dev Team';

    if (!prdContent) {
      throw new Error('PRD content is required for project orchestration');
    }

    this.logger.info('Starting project orchestration', { projectName });

    // Initialize project context
    const projectContext: ProjectContext = {
      id: `project_${Date.now()}`,
      name: projectName,
      description: projectDescription,
      phase: 'requirements_analysis',
      requirements: [],
      user_stories: [],
      decisions: [],
      artifacts: [],
    };

    this.updateContext(projectContext);

    // Initialize git repository
    await this.git.initialize(projectContext.id);

    try {
      // Phase 1: Requirements Analysis (Product Manager)
      this.logger.info('Phase 1: Requirements Analysis');
      await this.executePhase('requirements_analysis', prdContent);

      // Phase 2: Architecture Design (Tech Lead)
      this.logger.info('Phase 2: Architecture Design');
      await this.executePhase('architecture_design');

      // Phase 3: Development (Developer)
      this.logger.info('Phase 3: Development');
      await this.executePhase('development');

      // Phase 4: Testing (QA Engineer)
      this.logger.info('Phase 4: Testing');
      await this.executePhase('testing');

      // Phase 5: Deployment (DevOps Engineer)
      this.logger.info('Phase 5: Deployment');
      await this.executePhase('deployment');

      // Phase 6: Project Completion
      this.logger.info('Phase 6: Project Completion');
      await this.executePhase('complete');

      // Generate final project summary
      const projectSummary = await this.generateFinalProjectSummary();

      this.logger.info('Project orchestration completed successfully', { projectName });

      return { project_result: projectSummary };

    } catch (error) {
      this.logger.error('Project orchestration failed', { error, projectName });
      await this.handleProjectError(error as Error);
      throw error;
    }
  }

  private async executePhase(phase: ProjectPhase, prdContent?: string): Promise<void> {
    this.updateContext({ phase });

    switch (phase) {
      case 'requirements_analysis':
        await this.executeRequirementsPhase(prdContent!);
        break;
      case 'architecture_design':
        await this.executeArchitecturePhase();
        break;
      case 'development':
        await this.executeDevelopmentPhase();
        break;
      case 'testing':
        await this.executeTestingPhase();
        break;
      case 'deployment':
        await this.executeDeploymentPhase();
        break;
      case 'complete':
        await this.executeCompletionPhase();
        break;
    }

    // Validate phase completion
    await this.validatePhaseCompletion(phase);
  }

  private async executeRequirementsPhase(prdContent: string): Promise<void> {
    const pmAgent = this.agents.get('product_manager') as ProductManagerAgent;
    if (!pmAgent) throw new Error('Product Manager agent not available');

    // Task 1: Analyze requirements
    const analyzeTask: AgentTask = {
      id: `task_${Date.now()}_1`,
      title: 'analyze_requirements',
      description: 'Analyze PRD and extract structured requirements',
      assigned_to: 'product_manager',
      status: 'pending',
      priority: 'high',
      dependencies: [],
      result: { prd_content: prdContent },
      created_at: new Date().toISOString(),
    };

    const requirementsResult = await pmAgent.execute(analyzeTask);
    this.updateContext({ requirements: requirementsResult.requirements });

    // Task 2: Create user stories
    const userStoriesTask: AgentTask = {
      id: `task_${Date.now()}_2`,
      title: 'create_user_stories',
      description: 'Create user stories from requirements',
      assigned_to: 'product_manager',
      status: 'pending',
      priority: 'high',
      dependencies: [analyzeTask.id],
      result: {},
      created_at: new Date().toISOString(),
    };

    const userStoriesResult = await pmAgent.execute(userStoriesTask);
    this.updateContext({ user_stories: userStoriesResult.user_stories });

    // Task 3: Prioritize requirements
    const prioritizeTask: AgentTask = {
      id: `task_${Date.now()}_3`,
      title: 'prioritize_requirements',
      description: 'Prioritize requirements based on business value',
      assigned_to: 'product_manager',
      status: 'pending',
      priority: 'medium',
      dependencies: [userStoriesTask.id],
      result: {},
      created_at: new Date().toISOString(),
    };

    await pmAgent.execute(prioritizeTask);
  }

  private async executeArchitecturePhase(): Promise<void> {
    const tlAgent = this.agents.get('tech_lead') as TechLeadAgent;
    if (!tlAgent) throw new Error('Tech Lead agent not available');

    // Task 1: Create architecture
    const architectureTask: AgentTask = {
      id: `task_${Date.now()}_1`,
      title: 'create_architecture',
      description: 'Design system architecture',
      assigned_to: 'tech_lead',
      status: 'pending',
      priority: 'high',
      dependencies: [],
      result: {},
      created_at: new Date().toISOString(),
    };

    await tlAgent.execute(architectureTask);

    // Task 2: Define tech stack
    const techStackTask: AgentTask = {
      id: `task_${Date.now()}_2`,
      title: 'define_tech_stack',
      description: 'Define technology stack',
      assigned_to: 'tech_lead',
      status: 'pending',
      priority: 'high',
      dependencies: [architectureTask.id],
      result: {},
      created_at: new Date().toISOString(),
    };

    const techStackResult = await tlAgent.execute(techStackTask);
    this.updateContext({ tech_stack: techStackResult.tech_stack });

    // Task 3: Design API
    const apiTask: AgentTask = {
      id: `task_${Date.now()}_3`,
      title: 'design_api',
      description: 'Design API specifications',
      assigned_to: 'tech_lead',
      status: 'pending',
      priority: 'high',
      dependencies: [techStackTask.id],
      result: {},
      created_at: new Date().toISOString(),
    };

    const apiResult = await tlAgent.execute(apiTask);
    this.updateContext({ api_specs: apiResult.api_specs });

    // Task 4: Design database
    const dbTask: AgentTask = {
      id: `task_${Date.now()}_4`,
      title: 'design_database',
      description: 'Design database schema',
      assigned_to: 'tech_lead',
      status: 'pending',
      priority: 'high',
      dependencies: [apiTask.id],
      result: {},
      created_at: new Date().toISOString(),
    };

    const dbResult = await tlAgent.execute(dbTask);
    this.updateContext({ database_schema: dbResult.database_schema });
  }

  private async executeDevelopmentPhase(): Promise<void> {
    const devAgent = this.agents.get('developer') as DeveloperAgent;
    if (!devAgent) throw new Error('Developer agent not available');

    // Task 1: Create project structure
    const structureTask: AgentTask = {
      id: `task_${Date.now()}_1`,
      title: 'create_project_structure',
      description: 'Create project structure and configuration',
      assigned_to: 'developer',
      status: 'pending',
      priority: 'high',
      dependencies: [],
      result: { project_path: this.context.id },
      created_at: new Date().toISOString(),
    };

    await devAgent.execute(structureTask);

    // Task 2: Implement features
    const userStories = this.context.user_stories;
    for (let i = 0; i < userStories.length; i++) {
      const userStory = userStories[i];
      
      const featureTask: AgentTask = {
        id: `task_${Date.now()}_${i + 2}`,
        title: 'implement_feature',
        description: `Implement feature for user story: ${userStory.title}`,
        assigned_to: 'developer',
        status: 'pending',
        priority: userStory.priority,
        dependencies: [structureTask.id],
        result: { 
          project_path: this.context.id,
          user_story_id: userStory.id 
        },
        created_at: new Date().toISOString(),
      };

      const featureResult = await devAgent.execute(featureTask);
      this.updateContext({ 
        features: [...(this.context.features || []), featureResult.feature] 
      });
    }

    // Task 3: Write tests
    const testTask: AgentTask = {
      id: `task_${Date.now()}_${userStories.length + 2}`,
      title: 'write_tests',
      description: 'Write comprehensive tests for all features',
      assigned_to: 'developer',
      status: 'pending',
      priority: 'high',
      dependencies: [],
      result: { project_path: this.context.id },
      created_at: new Date().toISOString(),
    };

    await devAgent.execute(testTask);
  }

  private async executeTestingPhase(): Promise<void> {
    const qaAgent = this.agents.get('qa_engineer') as QAEngineerAgent;
    if (!qaAgent) throw new Error('QA Engineer agent not available');

    // Task 1: Create test plan
    const testPlanTask: AgentTask = {
      id: `task_${Date.now()}_1`,
      title: 'create_test_plan',
      description: 'Create comprehensive test plan',
      assigned_to: 'qa_engineer',
      status: 'pending',
      priority: 'high',
      dependencies: [],
      result: {},
      created_at: new Date().toISOString(),
    };

    await qaAgent.execute(testPlanTask);

    // Task 2: Write unit tests
    const unitTestTask: AgentTask = {
      id: `task_${Date.now()}_2`,
      title: 'write_unit_tests',
      description: 'Write unit tests for all features',
      assigned_to: 'qa_engineer',
      status: 'pending',
      priority: 'high',
      dependencies: [testPlanTask.id],
      result: { project_path: this.context.id },
      created_at: new Date().toISOString(),
    };

    await qaAgent.execute(unitTestTask);

    // Task 3: Write integration tests
    const integrationTestTask: AgentTask = {
      id: `task_${Date.now()}_3`,
      title: 'write_integration_tests',
      description: 'Write integration tests',
      assigned_to: 'qa_engineer',
      status: 'pending',
      priority: 'high',
      dependencies: [unitTestTask.id],
      result: { project_path: this.context.id },
      created_at: new Date().toISOString(),
    };

    await qaAgent.execute(integrationTestTask);

    // Task 4: Write e2e tests
    const e2eTestTask: AgentTask = {
      id: `task_${Date.now()}_4`,
      title: 'write_e2e_tests',
      description: 'Write end-to-end tests',
      assigned_to: 'qa_engineer',
      status: 'pending',
      priority: 'medium',
      dependencies: [integrationTestTask.id],
      result: { project_path: this.context.id },
      created_at: new Date().toISOString(),
    };

    await qaAgent.execute(e2eTestTask);

    // Task 5: Generate test report
    const testReportTask: AgentTask = {
      id: `task_${Date.now()}_5`,
      title: 'generate_test_report',
      description: 'Generate comprehensive test report',
      assigned_to: 'qa_engineer',
      status: 'pending',
      priority: 'medium',
      dependencies: [e2eTestTask.id],
      result: {},
      created_at: new Date().toISOString(),
    };

    await qaAgent.execute(testReportTask);
  }

  private async executeDeploymentPhase(): Promise<void> {
    const devopsAgent = this.agents.get('devops_engineer') as DevOpsEngineerAgent;
    if (!devopsAgent) throw new Error('DevOps Engineer agent not available');

    // Task 1: Setup deployment
    const deploymentTask: AgentTask = {
      id: `task_${Date.now()}_1`,
      title: 'setup_deployment',
      description: 'Setup deployment configuration',
      assigned_to: 'devops_engineer',
      status: 'pending',
      priority: 'high',
      dependencies: [],
      result: { 
        project_path: this.context.id,
        deployment_type: 'docker',
        environment: 'development'
      },
      created_at: new Date().toISOString(),
    };

    await devopsAgent.execute(deploymentTask);

    // Task 2: Create CI/CD pipeline
    const cicdTask: AgentTask = {
      id: `task_${Date.now()}_2`,
      title: 'create_cicd_pipeline',
      description: 'Create CI/CD pipeline',
      assigned_to: 'devops_engineer',
      status: 'pending',
      priority: 'high',
      dependencies: [deploymentTask.id],
      result: { project_path: this.context.id },
      created_at: new Date().toISOString(),
    };

    await devopsAgent.execute(cicdTask);

    // Task 3: Configure monitoring
    const monitoringTask: AgentTask = {
      id: `task_${Date.now()}_3`,
      title: 'configure_monitoring',
      description: 'Configure monitoring and observability',
      assigned_to: 'devops_engineer',
      status: 'pending',
      priority: 'medium',
      dependencies: [cicdTask.id],
      result: {},
      created_at: new Date().toISOString(),
    };

    await devopsAgent.execute(monitoringTask);

    // Task 4: Setup security
    const securityTask: AgentTask = {
      id: `task_${Date.now()}_4`,
      title: 'setup_security',
      description: 'Setup security configuration',
      assigned_to: 'devops_engineer',
      status: 'pending',
      priority: 'high',
      dependencies: [monitoringTask.id],
      result: {},
      created_at: new Date().toISOString(),
    };

    await devopsAgent.execute(securityTask);

    // Task 5: Create deployment docs
    const docsTask: AgentTask = {
      id: `task_${Date.now()}_5`,
      title: 'create_deployment_docs',
      description: 'Create deployment documentation',
      assigned_to: 'devops_engineer',
      status: 'pending',
      priority: 'medium',
      dependencies: [securityTask.id],
      result: {},
      created_at: new Date().toISOString(),
    };

    await devopsAgent.execute(docsTask);
  }

  private async executeCompletionPhase(): Promise<void> {
    // Create final project summary
    await this.createFinalProjectSummary();

    // Commit all changes
    if (config.git.enabled) {
      await this.git.commitChanges('feat: complete project implementation');
    }

    this.logger.info('Project completion phase finished');
  }

  private async validatePhaseCompletion(phase: ProjectPhase): Promise<void> {
    const validationTask: AgentTask = {
      id: `validation_${Date.now()}`,
      title: 'validate_phase',
      description: `Validate completion of ${phase} phase`,
      assigned_to: 'orchestrator',
      status: 'pending',
      priority: 'high',
      dependencies: [],
      result: { phase },
      created_at: new Date().toISOString(),
    };

    await this.validatePhase(validationTask);
  }

  private async manageWorkflow(task: AgentTask): Promise<{ workflow_status: any }> {
    const currentPhase = this.context.phase;
    const progress = this.calculateProgress();

    const workflowStatus = {
      current_phase: currentPhase,
      progress_percentage: progress,
      next_phase: this.getNextPhase(currentPhase),
      estimated_completion: this.estimateCompletion(progress),
      active_tasks: this.getActiveTasks(),
      completed_tasks: this.getCompletedTasks(),
    };

    this.logger.info('Workflow status updated', workflowStatus);

    return { workflow_status: workflowStatus };
  }

  private async assignTasks(task: AgentTask): Promise<{ assigned_tasks: any[] }> {
    const currentPhase = this.context.phase;
    const availableAgents = Array.from(this.agents.values()).filter(agent => agent.isEnabled());

    const assignedTasks = availableAgents.map(agent => ({
      agent_role: agent.getRole(),
      available_tasks: this.getAvailableTasksForAgent(agent.getRole(), currentPhase),
      current_load: this.getAgentLoad(agent.getRole()),
    }));

    return { assigned_tasks: assignedTasks };
  }

  private async monitorProgress(task: AgentTask): Promise<{ progress_report: any }> {
    const progress = {
      overall_progress: this.calculateProgress(),
      phase_progress: this.getPhaseProgress(),
      agent_status: this.getAgentStatus(),
      quality_metrics: this.getQualityMetrics(),
      risk_assessment: this.assessRisks(),
      recommendations: this.generateRecommendations(),
    };

    return { progress_report: progress };
  }

  private async validatePhase(task: AgentTask): Promise<{ validation_result: any }> {
    const phase = task.result?.phase;
    if (!phase) {
      throw new Error('Phase is required for validation');
    }

    const validationResult = {
      phase,
      is_complete: this.isPhaseComplete(phase),
      missing_artifacts: this.getMissingArtifacts(phase),
      quality_gates_passed: this.checkQualityGates(phase),
      next_steps: this.getNextSteps(phase),
    };

    return { validation_result: validationResult };
  }

  private async handleError(task: AgentTask): Promise<{ error_resolution: any }> {
    const error = task.result?.error;
    if (!error) {
      throw new Error('Error details are required for error handling');
    }

    const errorResolution = {
      error_type: this.classifyError(error),
      resolution_strategy: this.getResolutionStrategy(error),
      affected_components: this.getAffectedComponents(error),
      recovery_actions: this.getRecoveryActions(error),
      prevention_measures: this.getPreventionMeasures(error),
    };

    return { error_resolution: errorResolution };
  }

  private async generateProjectSummary(task: AgentTask): Promise<{ project_summary: any }> {
    const projectSummary = {
      project_info: {
        name: this.context.name,
        description: this.context.description,
        id: this.context.id,
        phase: this.context.phase,
      },
      artifacts: this.context.artifacts,
      decisions: this.context.decisions,
      statistics: {
        requirements_count: this.context.requirements?.length || 0,
        user_stories_count: this.context.user_stories?.length || 0,
        features_count: this.context.features?.length || 0,
        test_suites_count: this.context.test_suites?.length || 0,
      },
      quality_metrics: this.getQualityMetrics(),
      deployment_info: this.getDeploymentInfo(),
    };

    return { project_summary: projectSummary };
  }

  private initializeAgents(): void {
    this.agents.set('product_manager', new ProductManagerAgent(this.context));
    this.agents.set('tech_lead', new TechLeadAgent(this.context));
    this.agents.set('developer', new DeveloperAgent(this.context));
    this.agents.set('qa_engineer', new QAEngineerAgent(this.context));
    this.agents.set('devops_engineer', new DevOpsEngineerAgent(this.context));
  }

  private calculateProgress(): number {
    const phases = ['requirements_analysis', 'architecture_design', 'development', 'testing', 'deployment', 'complete'];
    const currentPhaseIndex = phases.indexOf(this.context.phase);
    return Math.round(((currentPhaseIndex + 1) / phases.length) * 100);
  }

  private getNextPhase(currentPhase: ProjectPhase): ProjectPhase | null {
    const phases = ['requirements_analysis', 'architecture_design', 'development', 'testing', 'deployment', 'complete'];
    const currentIndex = phases.indexOf(currentPhase);
    return currentIndex < phases.length - 1 ? phases[currentIndex + 1] as ProjectPhase : null;
  }

  private estimateCompletion(progress: number): string {
    const remainingWork = 100 - progress;
    const estimatedHours = Math.ceil(remainingWork / 10); // Rough estimate
    return `${estimatedHours} hours remaining`;
  }

  private getActiveTasks(): any[] {
    // This would be implemented based on actual task tracking
    return [];
  }

  private getCompletedTasks(): any[] {
    // This would be implemented based on actual task tracking
    return [];
  }

  private getAvailableTasksForAgent(agentRole: AgentRole, phase: ProjectPhase): string[] {
    // This would return available tasks based on agent role and current phase
    return [];
  }

  private getAgentLoad(agentRole: AgentRole): number {
    // This would return current load for the agent
    return 0;
  }

  private getPhaseProgress(): any {
    // This would return detailed progress for each phase
    return {};
  }

  private getAgentStatus(): any {
    // This would return status of all agents
    return {};
  }

  private getQualityMetrics(): any {
    // This would return quality metrics
    return {};
  }

  private assessRisks(): any {
    // This would assess project risks
    return {};
  }

  private generateRecommendations(): any {
    // This would generate recommendations
    return {};
  }

  private isPhaseComplete(phase: ProjectPhase): boolean {
    // This would check if phase is complete
    return true;
  }

  private getMissingArtifacts(phase: ProjectPhase): any[] {
    // This would return missing artifacts for the phase
    return [];
  }

  private checkQualityGates(phase: ProjectPhase): boolean {
    // This would check quality gates for the phase
    return true;
  }

  private getNextSteps(phase: ProjectPhase): any[] {
    // This would return next steps for the phase
    return [];
  }

  private classifyError(error: Error): string {
    // This would classify the error type
    return 'unknown';
  }

  private getResolutionStrategy(error: Error): any {
    // This would return resolution strategy
    return {};
  }

  private getAffectedComponents(error: Error): any[] {
    // This would return affected components
    return [];
  }

  private getRecoveryActions(error: Error): any[] {
    // This would return recovery actions
    return [];
  }

  private getPreventionMeasures(error: Error): any[] {
    // This would return prevention measures
    return [];
  }

  private getDeploymentInfo(): any {
    // This would return deployment information
    return {};
  }

  private async createFinalProjectSummary(): Promise<void> {
    const summaryPath = `${this.context.id}/docs`;
    await this.fs.ensureDirectory(summaryPath);

    const summaryDoc = `# Project Summary

**Project:** ${this.context.name}
**Date:** ${new Date().toISOString().split('T')[0]}
**Status:** Complete

## Project Overview

${this.context.description}

## Key Deliverables

- Requirements: ${this.context.requirements?.length || 0} requirements
- User Stories: ${this.context.user_stories?.length || 0} user stories
- Features: ${this.context.features?.length || 0} features implemented
- Test Suites: ${this.context.test_suites?.length || 0} test suites
- Documentation: Complete project documentation

## Technology Stack

${JSON.stringify(this.context.tech_stack, null, 2)}

## Architecture Decisions

${this.context.decisions.map(d => `- ${d.title}: ${d.description}`).join('\n')}

## Project Artifacts

${this.context.artifacts.map(a => `- ${a.name} (${a.type}): ${a.path}`).join('\n')}

## Next Steps

1. Review and validate the generated prototype
2. Deploy to staging environment for testing
3. Conduct user acceptance testing
4. Deploy to production environment
5. Monitor and maintain the application

This project was successfully completed by the MCP Autonomous Development Team.
`;

    await this.fs.writeFile(`${summaryPath}/project-summary.md`, summaryDoc);
    this.addArtifact('Project Summary', 'markdown', `${summaryPath}/project-summary.md`);
  }

  private async generateFinalProjectSummary(): Promise<any> {
    const summary = {
      project_info: {
        name: this.context.name,
        description: this.context.description,
        id: this.context.id,
        completion_date: new Date().toISOString(),
      },
      deliverables: {
        requirements: this.context.requirements?.length || 0,
        user_stories: this.context.user_stories?.length || 0,
        features: this.context.features?.length || 0,
        test_suites: this.context.test_suites?.length || 0,
        artifacts: this.context.artifacts?.length || 0,
      },
      technology_stack: this.context.tech_stack,
      architecture_decisions: this.context.decisions,
      project_artifacts: this.context.artifacts,
      quality_metrics: this.getQualityMetrics(),
      deployment_ready: true,
    };

    return summary;
  }

  private async handleProjectError(error: Error): Promise<void> {
    this.logger.error('Project error occurred', { error: error.message });
    
    // Create error report
    const errorReport = {
      timestamp: new Date().toISOString(),
      error: error.message,
      stack: error.stack,
      phase: this.context.phase,
      context: this.context,
    };

    const errorPath = `${this.context.id}/docs`;
    await this.fs.ensureDirectory(errorPath);
    await this.fs.writeFile(`${errorPath}/error-report.json`, JSON.stringify(errorReport, null, 2));
  }

  private async initializeGit(): Promise<void> {
    if (config.git.enabled) {
      try {
        await this.git.initialize();
        this.logger.info('Git repository initialized for project orchestration');
      } catch (error) {
        this.logger.warn('Failed to initialize Git repository', { error });
      }
    }
  }
}