import dotenv from 'dotenv';
import { z } from 'zod';

// Load environment variables
dotenv.config();

const ConfigSchema = z.object({
  // LLM Provider Configuration
  openai: z.object({
    apiKey: z.string().optional(),
    organization: z.string().optional(),
    model: z.string().default('gpt-4'),
  }),
  
  anthropic: z.object({
    apiKey: z.string().optional(),
    model: z.string().default('claude-3-sonnet-20240229'),
  }),
  
  local: z.object({
    endpoint: z.string().default('http://localhost:11434'),
    model: z.string().default('llama2'),
  }),
  
  // Default LLM Provider
  defaultProvider: z.enum(['openai', 'anthropic', 'local']).default('openai'),
  
  // Project Configuration
  project: z.object({
    defaultPath: z.string().default('./generated-projects'),
    templatesPath: z.string().default('./templates'),
    maxConcurrentTasks: z.number().default(3),
    timeoutMinutes: z.number().default(30),
  }),
  
  // Git Configuration
  git: z.object({
    enabled: z.boolean().default(true),
    autoCommit: z.boolean().default(true),
    commitMessage: z.string().default('Auto-generated by MCP Dev Team'),
    branch: z.string().default('main'),
  }),
  
  // File System Configuration
  filesystem: z.object({
    maxFileSize: z.number().default(10 * 1024 * 1024), // 10MB
    allowedExtensions: z.array(z.string()).default([
      '.js', '.ts', '.jsx', '.tsx', '.py', '.go', '.java', '.rb', '.php',
      '.html', '.css', '.scss', '.json', '.yaml', '.yml', '.md', '.txt',
      '.sql', '.sh', '.dockerfile', '.gitignore'
    ]),
  }),
  
  // Logging Configuration
  logging: z.object({
    level: z.enum(['debug', 'info', 'warn', 'error']).default('info'),
    format: z.enum(['json', 'text']).default('text'),
    enableFileLogging: z.boolean().default(false),
    logFilePath: z.string().default('./logs/mcp-dev-team.log'),
  }),
  
  // Security Configuration
  security: z.object({
    enableSandbox: z.boolean().default(true),
    allowedCommands: z.array(z.string()).default([
      'npm', 'yarn', 'pnpm', 'pip', 'poetry', 'go', 'cargo',
      'git', 'docker', 'docker-compose', 'kubectl'
    ]),
    blockedCommands: z.array(z.string()).default([
      'rm', 'del', 'format', 'dd', 'mkfs', 'fdisk'
    ]),
  }),
  
  // Agent Configuration
  agents: z.object({
    productManager: z.object({
      enabled: z.boolean().default(true),
      model: z.string().optional(),
      temperature: z.number().default(0.7),
    }),
    techLead: z.object({
      enabled: z.boolean().default(true),
      model: z.string().optional(),
      temperature: z.number().default(0.5),
    }),
    developer: z.object({
      enabled: z.boolean().default(true),
      model: z.string().optional(),
      temperature: z.number().default(0.3),
    }),
    qaEngineer: z.object({
      enabled: z.boolean().default(true),
      model: z.string().optional(),
      temperature: z.number().default(0.4),
    }),
    devopsEngineer: z.object({
      enabled: z.boolean().default(true),
      model: z.string().optional(),
      temperature: z.number().default(0.6),
    }),
  }),
  
  // Validation Configuration
  validation: z.object({
    enableCodeReview: z.boolean().default(true),
    enableSecurityScan: z.boolean().default(true),
    enableLinting: z.boolean().default(true),
    requireTests: z.boolean().default(true),
    minTestCoverage: z.number().default(80),
  }),
});

// Parse configuration from environment variables
const parseConfig = (): z.infer<typeof ConfigSchema> => {
  const envConfig = {
    openai: {
      apiKey: process.env.OPENAI_API_KEY,
      organization: process.env.OPENAI_ORG_ID,
      model: process.env.OPENAI_MODEL,
    },
    
    anthropic: {
      apiKey: process.env.ANTHROPIC_API_KEY,
      model: process.env.ANTHROPIC_MODEL,
    },
    
    local: {
      endpoint: process.env.LOCAL_LLM_ENDPOINT,
      model: process.env.LOCAL_LLM_MODEL,
    },
    
    defaultProvider: process.env.DEFAULT_LLM_PROVIDER as any,
    
    project: {
      defaultPath: process.env.PROJECT_DEFAULT_PATH,
      templatesPath: process.env.PROJECT_TEMPLATES_PATH,
      maxConcurrentTasks: process.env.MAX_CONCURRENT_TASKS ? parseInt(process.env.MAX_CONCURRENT_TASKS) : undefined,
      timeoutMinutes: process.env.TASK_TIMEOUT_MINUTES ? parseInt(process.env.TASK_TIMEOUT_MINUTES) : undefined,
    },
    
    git: {
      enabled: process.env.GIT_ENABLED === 'true',
      autoCommit: process.env.GIT_AUTO_COMMIT === 'true',
      commitMessage: process.env.GIT_COMMIT_MESSAGE,
      branch: process.env.GIT_BRANCH,
    },
    
    filesystem: {
      maxFileSize: process.env.MAX_FILE_SIZE ? parseInt(process.env.MAX_FILE_SIZE) : undefined,
      allowedExtensions: process.env.ALLOWED_EXTENSIONS ? process.env.ALLOWED_EXTENSIONS.split(',') : undefined,
    },
    
    logging: {
      level: process.env.LOG_LEVEL as any,
      format: process.env.LOG_FORMAT as any,
      enableFileLogging: process.env.ENABLE_FILE_LOGGING === 'true',
      logFilePath: process.env.LOG_FILE_PATH,
    },
    
    security: {
      enableSandbox: process.env.ENABLE_SANDBOX !== 'false',
      allowedCommands: process.env.ALLOWED_COMMANDS ? process.env.ALLOWED_COMMANDS.split(',') : undefined,
      blockedCommands: process.env.BLOCKED_COMMANDS ? process.env.BLOCKED_COMMANDS.split(',') : undefined,
    },
    
    agents: {
      productManager: {
        enabled: process.env.PM_ENABLED !== 'false',
        model: process.env.PM_MODEL,
        temperature: process.env.PM_TEMPERATURE ? parseFloat(process.env.PM_TEMPERATURE) : undefined,
      },
      techLead: {
        enabled: process.env.TL_ENABLED !== 'false',
        model: process.env.TL_MODEL,
        temperature: process.env.TL_TEMPERATURE ? parseFloat(process.env.TL_TEMPERATURE) : undefined,
      },
      developer: {
        enabled: process.env.DEV_ENABLED !== 'false',
        model: process.env.DEV_MODEL,
        temperature: process.env.DEV_TEMPERATURE ? parseFloat(process.env.DEV_TEMPERATURE) : undefined,
      },
      qaEngineer: {
        enabled: process.env.QA_ENABLED !== 'false',
        model: process.env.QA_MODEL,
        temperature: process.env.QA_TEMPERATURE ? parseFloat(process.env.QA_TEMPERATURE) : undefined,
      },
      devopsEngineer: {
        enabled: process.env.DEVOPS_ENABLED !== 'false',
        model: process.env.DEVOPS_MODEL,
        temperature: process.env.DEVOPS_TEMPERATURE ? parseFloat(process.env.DEVOPS_TEMPERATURE) : undefined,
      },
    },
    
    validation: {
      enableCodeReview: process.env.ENABLE_CODE_REVIEW !== 'false',
      enableSecurityScan: process.env.ENABLE_SECURITY_SCAN !== 'false',
      enableLinting: process.env.ENABLE_LINTING !== 'false',
      requireTests: process.env.REQUIRE_TESTS !== 'false',
      minTestCoverage: process.env.MIN_TEST_COVERAGE ? parseInt(process.env.MIN_TEST_COVERAGE) : undefined,
    },
  };

  return ConfigSchema.parse(envConfig);
};

export const config = parseConfig();

// Helper functions for configuration
export const getLLMConfig = (provider?: string) => {
  const targetProvider = provider || config.defaultProvider;
  
  switch (targetProvider) {
    case 'openai':
      return {
        provider: 'openai' as const,
        apiKey: config.openai.apiKey,
        model: config.openai.model,
        organization: config.openai.organization,
      };
    case 'anthropic':
      return {
        provider: 'anthropic' as const,
        apiKey: config.anthropic.apiKey,
        model: config.anthropic.model,
      };
    case 'local':
      return {
        provider: 'local' as const,
        endpoint: config.local.endpoint,
        model: config.local.model,
      };
    default:
      throw new Error(`Unsupported LLM provider: ${targetProvider}`);
  }
};

export const getAgentConfig = (agentRole: string) => {
  const agentConfigs = {
    product_manager: config.agents.productManager,
    tech_lead: config.agents.techLead,
    developer: config.agents.developer,
    qa_engineer: config.agents.qaEngineer,
    devops_engineer: config.agents.devopsEngineer,
  };
  
  return agentConfigs[agentRole as keyof typeof agentConfigs] || config.agents.developer;
};

export const isFeatureEnabled = (feature: string): boolean => {
  const featureMap = {
    'git': config.git.enabled,
    'sandbox': config.security.enableSandbox,
    'code_review': config.validation.enableCodeReview,
    'security_scan': config.validation.enableSecurityScan,
    'linting': config.validation.enableLinting,
    'tests': config.validation.requireTests,
  };
  
  return featureMap[feature as keyof typeof featureMap] ?? true;
};