import { z } from 'zod';
import { FileOperations } from '../utils/file-operations.js';

export const updateDocumentationSchema = z.object({
  projectPath: z.string().describe('Path to the project directory'),
  documentationType: z.enum(['readme', 'api', 'architecture', 'deployment', 'contributing', 'changelog']).describe('Type of documentation to update'),
  content: z.object({
    title: z.string().optional(),
    sections: z.array(z.object({
      heading: z.string(),
      content: z.string(),
      subsections: z.array(z.object({
        heading: z.string(),
        content: z.string()
      })).optional()
    }))
  }).optional().describe('Structured content for the documentation'),
  markdownContent: z.string().optional().describe('Raw markdown content to write'),
  appendMode: z.boolean().optional().describe('Whether to append to existing documentation'),
  autoGenerate: z.boolean().optional().describe('Whether to auto-generate documentation from code')
});

export async function updateDocumentation(args: z.infer<typeof updateDocumentationSchema>) {
  try {
    let finalContent = '';
    let filePath = '';

    // Determine file path based on documentation type
    switch (args.documentationType) {
      case 'readme':
        filePath = `${args.projectPath}/README.md`;
        break;
      case 'api':
        filePath = `${args.projectPath}/docs/API.md`;
        break;
      case 'architecture':
        filePath = `${args.projectPath}/docs/ARCHITECTURE.md`;
        break;
      case 'deployment':
        filePath = `${args.projectPath}/docs/DEPLOYMENT.md`;
        break;
      case 'contributing':
        filePath = `${args.projectPath}/CONTRIBUTING.md`;
        break;
      case 'changelog':
        filePath = `${args.projectPath}/CHANGELOG.md`;
        break;
    }

    // Generate content based on input
    if (args.markdownContent) {
      finalContent = args.markdownContent;
    } else if (args.content) {
      finalContent = generateMarkdownFromStructure(args.content, args.documentationType);
    } else if (args.autoGenerate) {
      finalContent = await autoGenerateDocumentation(args.projectPath, args.documentationType);
    } else {
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({
              success: false,
              error: 'No content provided for documentation update'
            }, null, 2)
          }
        ]
      };
    }

    // Handle append mode
    if (args.appendMode && await FileOperations.fileExists(filePath)) {
      const existingContent = await FileOperations.readFile(filePath);
      finalContent = existingContent + '\n\n' + finalContent;
    }

    // Write the documentation file
    await FileOperations.writeFile(filePath, finalContent);

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({
            success: true,
            message: `${args.documentationType} documentation updated successfully`,
            data: {
              filePath,
              documentationType: args.documentationType,
              size: finalContent.length,
              mode: args.appendMode ? 'append' : 'replace',
              preview: finalContent.substring(0, 200) + (finalContent.length > 200 ? '...' : '')
            }
          }, null, 2)
        }
      ]
    };
  } catch (error) {
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({
            success: false,
            error: `Documentation update failed: ${error.message}`
          }, null, 2)
        }
      ]
    };
  }
}

function generateMarkdownFromStructure(content: any, documentationType: string): string {
  let markdown = '';

  if (content.title) {
    markdown += `# ${content.title}\n\n`;
  }

  content.sections.forEach((section: any) => {
    markdown += `## ${section.heading}\n\n`;
    markdown += `${section.content}\n\n`;

    if (section.subsections) {
      section.subsections.forEach((subsection: any) => {
        markdown += `### ${subsection.heading}\n\n`;
        markdown += `${subsection.content}\n\n`;
      });
    }
  });

  return markdown;
}

async function autoGenerateDocumentation(projectPath: string, documentationType: string): Promise<string> {
  switch (documentationType) {
    case 'readme':
      return await generateReadmeDocumentation(projectPath);
    case 'api':
      return await generateApiDocumentation(projectPath);
    case 'architecture':
      return await generateArchitectureDocumentation(projectPath);
    case 'deployment':
      return await generateDeploymentDocumentation(projectPath);
    case 'contributing':
      return generateContributingDocumentation();
    case 'changelog':
      return generateChangelogDocumentation();
    default:
      return `# ${documentationType.charAt(0).toUpperCase() + documentationType.slice(1)} Documentation\n\nDocumentation content goes here.\n`;
  }
}

async function generateReadmeDocumentation(projectPath: string): Promise<string> {
  // Read package.json for project info
  let projectInfo: any = {};
  try {
    const packageJsonPath = `${projectPath}/package.json`;
    if (await FileOperations.fileExists(packageJsonPath)) {
      const packageContent = await FileOperations.readFile(packageJsonPath);
      projectInfo = JSON.parse(packageContent);
    }
  } catch (error) {
    // Ignore package.json parsing errors
  }

  const projectName = projectInfo.name || 'Project';
  const description = projectInfo.description || 'A generated project';

  return `# ${projectName}

## Description

${description}

## Installation

\`\`\`bash
npm install
\`\`\`

## Usage

\`\`\`bash
# Development
npm run dev

# Build
npm run build

# Start
npm start

# Test
npm test
\`\`\`

## Scripts

${projectInfo.scripts ? Object.entries(projectInfo.scripts).map(([name, script]) => 
  `- \`npm run ${name}\`: ${script}`
).join('\n') : 'No scripts defined'}

## Dependencies

### Production Dependencies
${projectInfo.dependencies ? Object.keys(projectInfo.dependencies).map(dep => `- ${dep}`).join('\n') : 'None'}

### Development Dependencies
${projectInfo.devDependencies ? Object.keys(projectInfo.devDependencies).map(dep => `- ${dep}`).join('\n') : 'None'}

## Contributing

Please read CONTRIBUTING.md for details on our code of conduct and the process for submitting pull requests.

## License

${projectInfo.license || 'No license specified'}
`;
}

async function generateApiDocumentation(projectPath: string): Promise<string> {
  // Scan for API routes and controllers
  const apiFiles = await findApiFiles(projectPath);
  
  let documentation = `# API Documentation

## Overview

This document describes the API endpoints available in this application.

## Base URL

\`\`\`
http://localhost:3000/api
\`\`\`

## Authentication

Most endpoints require authentication via JWT token in the Authorization header:

\`\`\`
Authorization: Bearer <your-jwt-token>
\`\`\`

## Endpoints

`;

  // Extract endpoints from files
  for (const file of apiFiles) {
    try {
      const content = await FileOperations.readFile(file);
      const endpoints = extractEndpoints(content);
      
      if (endpoints.length > 0) {
        documentation += `### ${file.split('/').pop()}\n\n`;
        endpoints.forEach(endpoint => {
          documentation += `#### ${endpoint.method} ${endpoint.path}\n\n`;
          documentation += `${endpoint.description}\n\n`;
          
          if (endpoint.parameters.length > 0) {
            documentation += `**Parameters:**\n`;
            endpoint.parameters.forEach(param => {
              documentation += `- \`${param.name}\` (${param.type}): ${param.description}\n`;
            });
            documentation += '\n';
          }
          
          documentation += `**Response:**\n\`\`\`json\n${endpoint.response}\n\`\`\`\n\n`;
        });
      }
    } catch (error) {
      // Skip files that can't be read
    }
  }

  return documentation;
}

async function generateArchitectureDocumentation(projectPath: string): Promise<string> {
  return `# Architecture Documentation

## Overview

This document describes the system architecture and design decisions.

## System Architecture

### High-Level Architecture

The application follows a layered architecture pattern:

\`\`\`
┌─────────────────┐
│   Frontend      │
│   (React/Vue)   │
└─────────────────┘
         │
┌─────────────────┐
│   API Gateway   │
│   (Express.js)  │
└─────────────────┘
         │
┌─────────────────┐
│   Services      │
│   (Business     │
│    Logic)       │
└─────────────────┘
         │
┌─────────────────┐
│   Data Access   │
│   (Repository   │
│    Pattern)     │
└─────────────────┘
         │
┌─────────────────┐
│   Database      │
│   (PostgreSQL)  │
└─────────────────┘
\`\`\`

## Components

### Frontend Layer
- Handles user interactions
- Manages application state
- Communicates with backend APIs

### API Gateway
- Routes incoming requests
- Handles authentication and authorization
- Implements rate limiting and validation

### Service Layer
- Contains business logic
- Orchestrates data operations
- Implements domain rules

### Data Access Layer
- Abstracts database operations
- Implements repository pattern
- Handles data mapping

### Database Layer
- Persistent data storage
- Ensures data integrity
- Provides ACID transactions

## Design Patterns

- **Repository Pattern**: Abstracts data access
- **Service Layer Pattern**: Encapsulates business logic
- **Dependency Injection**: Manages component dependencies
- **MVC Pattern**: Separates concerns in API layer

## Technology Stack

- **Frontend**: React with TypeScript
- **Backend**: Node.js with Express
- **Database**: PostgreSQL
- **Authentication**: JWT tokens
- **Testing**: Jest and Playwright
- **Deployment**: Docker containers

## Security Considerations

- JWT token-based authentication
- Input validation and sanitization
- HTTPS encryption
- Rate limiting
- SQL injection prevention
- XSS protection

## Performance Considerations

- Database indexing
- Connection pooling
- Caching strategies
- Load balancing
- Code splitting
`;
}

async function generateDeploymentDocumentation(projectPath: string): Promise<string> {
  const hasDockerfile = await FileOperations.fileExists(`${projectPath}/Dockerfile`);
  const hasDockerCompose = await FileOperations.fileExists(`${projectPath}/docker-compose.yml`);
  const hasK8s = await FileOperations.fileExists(`${projectPath}/k8s`);

  return `# Deployment Documentation

## Overview

This document describes how to deploy the application in different environments.

## Prerequisites

- Docker and Docker Compose
- Node.js 18+ (for local development)
${hasK8s ? '- Kubernetes cluster (for production)' : ''}
- PostgreSQL database

## Environment Variables

Create a \`.env\` file based on \`.env.example\`:

\`\`\`bash
cp .env.example .env
\`\`\`

Update the following variables:
- \`DATABASE_URL\`: PostgreSQL connection string
- \`JWT_SECRET\`: Secret key for JWT tokens
- \`NODE_ENV\`: Environment (development/staging/production)

## Local Development

${hasDockerCompose ? `### Using Docker Compose (Recommended)

\`\`\`bash
docker-compose up -d
\`\`\`

This will start:
- Application server on port 3000
- PostgreSQL database on port 5432
- Redis (if configured) on port 6379

### Manual Setup` : '### Setup'}

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Start database:
   \`\`\`bash
   # Using Docker
   docker run -d --name postgres \\
     -e POSTGRES_DB=app_dev \\
     -e POSTGRES_USER=postgres \\
     -e POSTGRES_PASSWORD=password \\
     -p 5432:5432 \\
     postgres:15-alpine
   \`\`\`

3. Run migrations:
   \`\`\`bash
   npm run migrate
   \`\`\`

4. Start development server:
   \`\`\`bash
   npm run dev
   \`\`\`

## Production Deployment

${hasK8s ? `### Kubernetes (Recommended)

1. Build and push Docker image:
   \`\`\`bash
   docker build -t your-registry/app:latest .
   docker push your-registry/app:latest
   \`\`\`

2. Update image tag in \`k8s/deployment.yml\`

3. Apply Kubernetes manifests:
   \`\`\`bash
   kubectl apply -f k8s/
   \`\`\`

### Docker Deployment` : '### Docker Deployment'}

${hasDockerfile ? `1. Build Docker image:
   \`\`\`bash
   docker build -t app:latest .
   \`\`\`

2. Run container:
   \`\`\`bash
   docker run -d \\
     --name app \\
     -p 3000:3000 \\
     -e DATABASE_URL="your-database-url" \\
     -e JWT_SECRET="your-jwt-secret" \\
     app:latest
   \`\`\`

### Traditional Deployment` : '### Traditional Deployment'}

1. Build application:
   \`\`\`bash
   npm run build
   \`\`\`

2. Start with PM2:
   \`\`\`bash
   npm install -g pm2
   pm2 start dist/index.js --name app
   \`\`\`

## Health Checks

The application provides health check endpoints:

- \`GET /health\`: Basic health check
- \`GET /health/db\`: Database connectivity check

## Monitoring

### Logs

Application logs are written to:
- Console (development)
- Files in \`logs/\` directory (production)

### Metrics

Monitor these key metrics:
- Response time
- Error rate
- Database connections
- Memory usage
- CPU usage

## Backup and Recovery

### Database Backup

\`\`\`bash
# Create backup
pg_dump $DATABASE_URL > backup.sql

# Restore backup
psql $DATABASE_URL < backup.sql
\`\`\`

### Application Data

Ensure regular backups of:
- Database
- File uploads (if any)
- Configuration files

## Troubleshooting

### Common Issues

1. **Database connection errors**
   - Check DATABASE_URL environment variable
   - Verify database is running and accessible

2. **JWT token errors**
   - Verify JWT_SECRET is set
   - Check token expiration

3. **Port conflicts**
   - Ensure port 3000 is available
   - Update PORT environment variable if needed

### Logs

Check application logs for detailed error information:

\`\`\`bash
# Docker logs
docker logs app

# PM2 logs
pm2 logs app

# Kubernetes logs
kubectl logs deployment/app-deployment
\`\`\`
`;
}

function generateContributingDocumentation(): string {
  return `# Contributing Guidelines

## Welcome!

Thank you for your interest in contributing to this project! This document provides guidelines and instructions for contributors.

## Development Setup

1. Fork the repository
2. Clone your fork:
   \`\`\`bash
   git clone https://github.com/your-username/project-name.git
   \`\`\`
3. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`
4. Create a branch for your feature:
   \`\`\`bash
   git checkout -b feature/your-feature-name
   \`\`\`

## Development Workflow

### Code Style

- Use TypeScript for type safety
- Follow ESLint configuration
- Use Prettier for code formatting
- Write meaningful commit messages

### Testing

- Write unit tests for new features
- Ensure all tests pass before submitting
- Maintain or improve test coverage

\`\`\`bash
# Run tests
npm test

# Run tests with coverage
npm run test:coverage
\`\`\`

### Pull Request Process

1. **Update your branch** with the latest changes:
   \`\`\`bash
   git fetch upstream
   git rebase upstream/main
   \`\`\`

2. **Ensure quality checks pass**:
   \`\`\`bash
   npm run lint
   npm run test
   npm run build
   \`\`\`

3. **Create descriptive pull request**:
   - Clear title describing the change
   - Detailed description of what was changed and why
   - Reference any related issues
   - Include screenshots for UI changes

4. **Review process**:
   - All PRs require review from maintainers
   - Address any feedback promptly
   - Keep PR scope focused and manageable

## Issue Guidelines

### Reporting Bugs

When reporting bugs, please include:
- Clear description of the issue
- Steps to reproduce
- Expected vs actual behavior
- Environment details (OS, Node version, etc.)
- Screenshots if applicable

### Feature Requests

For feature requests, please provide:
- Clear description of the feature
- Use case and business value
- Proposed implementation approach
- Any relevant mockups or examples

## Code Review Checklist

Before submitting code, ensure:
- [ ] Code follows project style guidelines
- [ ] Tests are written and passing
- [ ] Documentation is updated if needed
- [ ] No sensitive information is committed
- [ ] Performance impact is considered
- [ ] Accessibility guidelines are followed (for UI changes)

## Getting Help

- Check existing issues and documentation
- Ask questions in discussions
- Contact maintainers if needed

## Recognition

Contributors will be recognized in:
- GitHub contributors list
- Project README
- Release notes for significant contributions

Thank you for contributing! 🎉
`;
}

function generateChangelogDocumentation(): string {
  const currentDate = new Date().toISOString().split('T')[0];
  
  return `# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- Initial project setup
- Basic authentication system
- API endpoints for core functionality
- Comprehensive test suite
- Docker deployment configuration
- CI/CD pipeline setup

### Changed
- Nothing yet

### Deprecated
- Nothing yet

### Removed
- Nothing yet

### Fixed
- Nothing yet

### Security
- JWT-based authentication
- Input validation and sanitization
- HTTPS encryption support

## [1.0.0] - ${currentDate}

### Added
- Initial release
- Core application functionality
- Basic documentation
- Deployment configurations

---

## How to Update This Changelog

When making changes to the project:

1. Add entries under the "Unreleased" section
2. Use the following categories:
   - **Added** for new features
   - **Changed** for changes in existing functionality
   - **Deprecated** for soon-to-be removed features
   - **Removed** for now removed features
   - **Fixed** for any bug fixes
   - **Security** for security-related changes

3. When releasing a new version:
   - Move "Unreleased" items to a new version section
   - Add the release date
   - Create a new "Unreleased" section

### Format Example:

\`\`\`markdown
## [1.1.0] - 2024-01-15

### Added
- New user dashboard feature
- Email notification system

### Fixed
- Login redirect issue
- Memory leak in background jobs
\`\`\`
`;
}

async function findApiFiles(projectPath: string): Promise<string[]> {
  const apiFiles: string[] = [];
  
  try {
    // Look for common API file patterns
    const searchPaths = [
      `${projectPath}/src/controllers`,
      `${projectPath}/src/routes`,
      `${projectPath}/src/api`,
      `${projectPath}/controllers`,
      `${projectPath}/routes`,
      `${projectPath}/api`
    ];

    for (const searchPath of searchPaths) {
      const files = await FileOperations.listFiles(searchPath, true);
      const jsFiles = files.filter(file => 
        file.endsWith('.js') || file.endsWith('.ts') || file.endsWith('.jsx') || file.endsWith('.tsx')
      );
      apiFiles.push(...jsFiles);
    }
  } catch (error) {
    // Directory doesn't exist, continue
  }

  return apiFiles;
}

function extractEndpoints(content: string): any[] {
  const endpoints: any[] = [];
  
  // Simple regex patterns to extract API endpoints
  const routePatterns = [
    /router\.(get|post|put|delete|patch)\s*\(\s*['"`]([^'"`]+)['"`]/g,
    /app\.(get|post|put|delete|patch)\s*\(\s*['"`]([^'"`]+)['"`]/g,
    /@(Get|Post|Put|Delete|Patch)\s*\(\s*['"`]([^'"`]+)['"`]/g
  ];

  routePatterns.forEach(pattern => {
    let match;
    while ((match = pattern.exec(content)) !== null) {
      endpoints.push({
        method: match[1].toUpperCase(),
        path: match[2],
        description: `API endpoint for ${match[2]}`,
        parameters: [],
        response: '{\n  "success": true,\n  "data": {}\n}'
      });
    }
  });

  return endpoints;
}